#ifndef MESSAGE_CODES_H
#define MESSAGE_CODES_H

#define REQ_PASSWRD  5
#define ACCEPT_PASSWRD 6
#define CHARLIM_PASSWRD 7
#define DENY_PASSWRD 8
#define TIMEOUT_ERR 9
#define FILE_UPLOAD_REQ 10
#define FILE_DOWNLOAD_REQ 11
#define FILE_UPLOAD_ACK 12
#define FILE_UPLOAD_DENY 13

#endif
